language: python
python:
- '3.6'
cache: pip
install:
- python --version
- echo $TRAVIS_BRANCH
- pip install -r requirements.txt
script:
- export PYTHONPATH=$PWD:$PYTHONPATH
- DOCKER=1 pytest -W ignore::DeprecationWarning -W ignore::UserWarning tests
