language: python
python:
- '3.6'
- '2.7'
cache: pip
install:
- python --version
- pip install scipy
- pip install pytest
- pip install lygadgets
- pip install lytest==0.0.8
script:
- DOCKER=1 pytest tests
